INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Root', NULL);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Książki', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Biografie', 2);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Kuchnia', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Fantastyka', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Muzyka', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Pop', 6);


INSERT INTO ADDRESSES (ADD_CITY, ADD_STREET) VALUES ('Kraków', 'Budryka 13');
INSERT INTO ADDRESSES (ADD_CITY, ADD_STREET) VALUES ('Kraków', 'Lubicz 1');
INSERT INTO ADDRESSES (ADD_CITY, ADD_STREET) VALUES ('Kraków', 'Al. Jana Pawła III');

INSERT INTO CUSTOMERS (CUS_FIRST_NAME, CUS_LAST_NAME, CUS_ADD_ID)
VALUES ('Andrzej', 'Dudeł', 1);
INSERT INTO CUSTOMERS (CUS_FIRST_NAME, CUS_LAST_NAME, CUS_ADD_ID)
VALUES ('Karlos', 'Santana', 2);
INSERT INTO CUSTOMERS (CUS_FIRST_NAME, CUS_LAST_NAME, CUS_ADD_ID)
VALUES ('Michał', 'Białkow', 3);

INSERT INTO PRODUCT_TYPES (PTYP_NAME) VALUES ('Fizyczny');
INSERT INTO PRODUCT_TYPES (PTYP_NAME) VALUES ('Wirtualny');
INSERT INTO PRODUCT_TYPES (PTYP_NAME) VALUES ('DRM');

INSERT INTO DIGITAL_RESOURCES (DRES_NAME, DRES_FILENAME, DRES_MAX_DOWNLOAD)
VALUES ('Parostatkiem W Piękny Rejs', 'parostatkiem.mp3', '10');
INSERT INTO DIGITAL_RESOURCES (DRES_NAME, DRES_FILENAME, DRES_MAX_DOWNLOAD)
VALUES ('Chciałbym Być', 'chcialbym_byc.mp3', '10');
INSERT INTO DIGITAL_RESOURCES (DRES_NAME, DRES_FILENAME, DRES_MAX_DOWNLOAD)
VALUES ('Bo Jesteś Ty', 'bo_jestes_ty.mp3', '10');


INSERT INTO PRODUCTS (PRD_NAME, PRD_PRICE, PRD_IMG, PRD_ISBN, PRD_CAT_ID, PRD_PTYP_ID, PRD_DRES_ID)
VALUES ('Elon Musk. Biografia twórcy PayPal, Tesla, SpaceX',
42, 'elon_musk.png', '978-83-240-3440-6', 3, 1, NULL
);
