/**
 * Księgarnia internetowa
 * Maciej Krawiec
 */

-- drop
DROP TABLE SALES_PRODUCTS;
DROP TABLE SALES;
DROP TABLE RETURNS;
DROP TABLE CUSTOMERS_ORDERS;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE DIGITAL_RESOURCES;
DROP TABLE PRODUCT_TYPES;
DROP TABLE CUSTOMERS;
DROP TABLE ADDRESSES;
DROP TABLE CATEGORIES;


-- create
CREATE TABLE CATEGORIES (
    CAT_ID          number(10) NOT NULL,
    CAT_NAME        varchar2(255) NOT NULL,
    CAT_PARENT_ID   number(10)
);

ALTER TABLE CATEGORIES
ADD CONSTRAINT CST_PK_CATEGORIES PRIMARY KEY (CAT_ID);

ALTER TABLE CATEGORIES
ADD CONSTRAINT CST_FK_CATEGORIES_PARENT FOREIGN KEY (CAT_PARENT_ID)
        REFERENCES CATEGORIES (CAT_ID);

CREATE TABLE ADDRESSES (
    ADD_ID          number(10) NOT NULL,
    ADD_STREET      varchar2(255) NOT NULL,
    ADD_CITY        varchar2(255) NOT NULL
);

ALTER TABLE ADDRESSES
ADD CONSTRAINT CST_PK_ADDRESSES PRIMARY KEY (ADD_ID);

CREATE TABLE CUSTOMERS (
    CUS_ID          number(10) NOT NULL,
    CUS_FIRST_NAME  varchar2(255) NOT NULL,
    CUS_LAST_NAME   varchar2(255) NOT NULL,
    CUS_ADD_ID      number(10) NOT NULL
);

ALTER TABLE CUSTOMERS
ADD CONSTRAINT CST_PK_CUSTOMERS PRIMARY KEY (CUS_ID);

ALTER TABLE CUSTOMERS
ADD CONSTRAINT CST_FK_CUSTOMERS_ADD FOREIGN KEY (CUS_ADD_ID)
        REFERENCES ADDRESSES (ADD_ID);

CREATE TABLE PRODUCT_TYPES (
    PTYP_ID          number(10) NOT NULL,
    PTYP_NAME        varchar2(255) NOT NULL
);

ALTER TABLE PRODUCT_TYPES
ADD CONSTRAINT CST_PK_PRODUCT_TYPES PRIMARY KEY (PTYP_ID);

CREATE TABLE DIGITAL_RESOURCES (
    DRES_ID             number(10) NOT NULL,
    DRES_NAME           varchar2(255) NOT NULL,
    DRES_FILENAME       varchar2(255) NOT NULL,
    DRES_MAX_DOWNLOAD   number(3) NOT NULL
);

ALTER TABLE DIGITAL_RESOURCES
ADD CONSTRAINT CST_PK_DIGITAL_RESOURCES PRIMARY KEY (DRES_ID);

CREATE TABLE PRODUCTS (
    PRD_ID          number(10) NOT NULL,
    PRD_NAME        varchar2(255) NOT NULL,
    PRD_PRICE       number(4) NOT NULL,
    PRD_IMG         varchar2(255) NOT NULL,
    PRD_ISBN        varchar2(17) NOT NULL,
    PRD_CAT_ID      number(10) NOT NULL,
    PRD_PTYP_ID     number(10) NOT NULL,
    PRD_DRES_ID     number(10)
);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CST_PK_PRODUCTS PRIMARY KEY (PRD_ID);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CST_FK_PRODUCTS_CAT FOREIGN KEY (PRD_CAT_ID)
        REFERENCES CATEGORIES (CAT_ID);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CST_FK_PRODUCTS_PTYP FOREIGN KEY (PRD_PTYP_ID)
        REFERENCES PRODUCT_TYPES (PTYP_ID);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CST_FK_PRODUCTS_DRES FOREIGN KEY (PRD_DRES_ID)
        REFERENCES DIGITAL_RESOURCES (DRES_ID);

CREATE TABLE ORDERS (
    ORD_ID          number(10) NOT NULL,
    ORD_PRD_ID      number(10) NOT NULL
);

ALTER TABLE ORDERS
ADD CONSTRAINT CST_PK_ORDERS PRIMARY KEY (ORD_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT CST_FK_ORDERS_PRD FOREIGN KEY (ORD_PRD_ID)
        REFERENCES PRODUCTS (PRD_ID);

CREATE TABLE CUSTOMERS_ORDERS (
    CUS_ID          number(10) NOT NULL,
    ORD_ID          number(10) NOT NULL
);

ALTER TABLE CUSTOMERS_ORDERS
ADD CONSTRAINT CST_PK_CUSTOMERS_ORDERS PRIMARY KEY (CUS_ID, ORD_ID);

ALTER TABLE CUSTOMERS_ORDERS
ADD CONSTRAINT CST_FK_CUSTOMERS_ORDERS_CUS FOREIGN KEY (CUS_ID)
        REFERENCES CUSTOMERS (CUS_ID);

ALTER TABLE CUSTOMERS_ORDERS
ADD CONSTRAINT CST_FK_CUSTOMERS_ORDERS_ORD FOREIGN KEY (ORD_ID)
        REFERENCES ORDERS (ORD_ID);

CREATE TABLE RETURNS (
    RET_ID          number(10) NOT NULL,
    RET_ORD_ID      number(10) NOT NULL,
    RET_REASON      clob
);

ALTER TABLE RETURNS ADD CONSTRAINT CST_PK_RETURNS PRIMARY KEY (RET_ID);

ALTER TABLE RETURNS
ADD CONSTRAINT CST_FK_RETURNS_ORD FOREIGN KEY (RET_ORD_ID)
        REFERENCES ORDERS (ORD_ID);

CREATE TABLE SALES (
    SAL_ID          number(10) NOT NULL,
    SAL_NAME        varchar2(255) NOT NULL,
    SAL_REDUCTION   number(3) NOT NULL
);

ALTER TABLE SALES
ADD CONSTRAINT CST_PK_SALES PRIMARY KEY (SAL_ID);

CREATE TABLE SALES_PRODUCTS (
    SAL_ID          number(10) NOT NULL,
    PRD_ID          number(10) NOT NULL
);

ALTER TABLE SALES_PRODUCTS
ADD CONSTRAINT CST_PK_SALES_PRODUCTS PRIMARY KEY (SAL_ID, PRD_ID);

ALTER TABLE SALES_PRODUCTS
ADD CONSTRAINT CST_FK_SALES_PRODUCTS_SAL FOREIGN KEY (SAL_ID)
        REFERENCES SALES (SAL_ID);

ALTER TABLE SALES_PRODUCTS
ADD CONSTRAINT CST_FK_SALES_PRODUCTS_PRD FOREIGN KEY (PRD_ID)
        REFERENCES PRODUCTS (PRD_ID);

-- sequences

DROP SEQUENCE SEQ_SALES;
DROP SEQUENCE SEQ_SALES_PRODUCTS;
DROP SEQUENCE SEQ_RETURNS;
DROP SEQUENCE SEQ_CUSTOMERS_ORDERS;
DROP SEQUENCE SEQ_ORDERS;
DROP SEQUENCE SEQ_PRODUCTS;
DROP SEQUENCE SEQ_DIGITAL_RESOURCES;
DROP SEQUENCE SEQ_PRODUCT_TYPES;
DROP SEQUENCE SEQ_CUSTOMERS;
DROP SEQUENCE SEQ_ADDRESSES;
DROP SEQUENCE SEQ_CATEGORIES;

CREATE SEQUENCE SEQ_SALES INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_SALES_PRODUCTS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_RETURNS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_CUSTOMERS_ORDERS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_ORDERS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_PRODUCTS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_DIGITAL_RESOURCES INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_PRODUCT_TYPES INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_CUSTOMERS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_ADDRESSES INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;
CREATE SEQUENCE SEQ_CATEGORIES INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;

-- triggers

CREATE OR REPLACE TRIGGER T_BI_SALES
  before insert on SALES
  for each row
begin
  if :NEW.SAL_ID is null then
    select SEQ_SALES.nextval into :NEW.SAL_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_RETURNS
  before insert on RETURNS
  for each row
begin
  if :NEW.RET_ID is null then
    select SEQ_RETURNS.nextval into :NEW.RET_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_ORDERS
  before insert on ORDERS
  for each row
begin
  if :NEW.ORD_ID is null then
    select SEQ_ORDERS.nextval into :NEW.ORD_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_PRODUCTS
  before insert on PRODUCTS
  for each row
begin
  if :NEW.PRD_ID is null then
    select SEQ_PRODUCTS.nextval into :NEW.PRD_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_DIGITAL_RESOURCES
  before insert on DIGITAL_RESOURCES
  for each row
begin
  if :NEW.DRES_ID is null then
    select SEQ_DIGITAL_RESOURCES.nextval into :NEW.DRES_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_PRODUCT_TYPES
  before insert on PRODUCT_TYPES
  for each row
begin
  if :NEW.PTYP_ID is null then
    select SEQ_PRODUCT_TYPES.nextval into :NEW.PTYP_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_CUSTOMERS
  before insert on CUSTOMERS
  for each row
begin
  if :NEW.CUS_ID is null then
    select SEQ_CUSTOMERS.nextval into :NEW.CUS_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_ADDRESSES
  before insert on ADDRESSES
  for each row
begin
  if :NEW.ADD_ID is null then
    select SEQ_ADDRESSES.nextval into :NEW.ADD_ID from dual;
  end if;
end;
/

CREATE OR REPLACE TRIGGER T_BI_CATEGORIES
  before insert on CATEGORIES
  for each row
begin
  if :NEW.CAT_ID is null then
    select SEQ_CATEGORIES.nextval into :NEW.CAT_ID from dual;
  end if;
end;
/


INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Root', NULL);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Książki', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Biografie', 2);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Kuchnia', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Fantastyka', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Muzyka', 1);
INSERT INTO CATEGORIES (CAT_NAME, CAT_PARENT_ID) VALUES ('Pop', 6);


INSERT INTO ADDRESSES (ADD_CITY, ADD_STREET) VALUES ('Kraków', 'Budryka 13');
INSERT INTO ADDRESSES (ADD_CITY, ADD_STREET) VALUES ('Kraków', 'Lubicz 1');
INSERT INTO ADDRESSES (ADD_CITY, ADD_STREET) VALUES ('Kraków', 'Al. Jana Pawła III');

INSERT INTO CUSTOMERS (CUS_FIRST_NAME, CUS_LAST_NAME, CUS_ADD_ID)
VALUES ('Andrzej', 'Dudeł', 1);
INSERT INTO CUSTOMERS (CUS_FIRST_NAME, CUS_LAST_NAME, CUS_ADD_ID)
VALUES ('Karlos', 'Santana', 2);
INSERT INTO CUSTOMERS (CUS_FIRST_NAME, CUS_LAST_NAME, CUS_ADD_ID)
VALUES ('Michał', 'Białkow', 3);

INSERT INTO PRODUCT_TYPES (PTYP_NAME) VALUES ('Fizyczny');
INSERT INTO PRODUCT_TYPES (PTYP_NAME) VALUES ('Wirtualny');
INSERT INTO PRODUCT_TYPES (PTYP_NAME) VALUES ('DRM');

INSERT INTO DIGITAL_RESOURCES (DRES_NAME, DRES_FILENAME, DRES_MAX_DOWNLOAD)
VALUES ('Parostatkiem W Piękny Rejs', 'parostatkiem.mp3', '10');
INSERT INTO DIGITAL_RESOURCES (DRES_NAME, DRES_FILENAME, DRES_MAX_DOWNLOAD)
VALUES ('Chciałbym Być', 'chcialbym_byc.mp3', '10');
INSERT INTO DIGITAL_RESOURCES (DRES_NAME, DRES_FILENAME, DRES_MAX_DOWNLOAD)
VALUES ('Bo Jesteś Ty', 'bo_jestes_ty.mp3', '10');


INSERT INTO PRODUCTS (PRD_NAME, PRD_PRICE, PRD_IMG, PRD_ISBN, PRD_CAT_ID, PRD_PTYP_ID, PRD_DRES_ID)
VALUES ('Elon Musk. Biografia twórcy PayPal, Tesla, SpaceX',
42, 'elon_musk.png', '978-83-240-3440-6', 3, 1, NULL
);
